complete flow

diff --git a/.github/workflows/expressions.yaml b/.github/workflows/expressions.yaml
--- a/.github/workflows/expressions.yaml
+++ b/.github/workflows/expressions.yaml
@@ -52,3 +52,43 @@ jobs:
           OVERWRITTEN: 'Overwritten at step level'
         run: |
           echo "Overwritten var: $OVERWRITTEN"
+
+  functions-pr-data:
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Print PR Info"
+        if: ${{ github.event_name == 'pull_request' }}
+        run: |
+          echo "PR Title: ${{ github.event.pull_request.title }}"
+          echo "PR Labels:"
+          cat << EOF
+          ${{ toJSON(github.event.pull_request.labels) }}
+          EOF
+
+      - name: "Bug Check"
+        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
+        run: echo "This PR fixes a bug."
+
+      - name: "Sleep and Cancel"
+        run: sleep 20
+
+      - name: "Failing Step"
+        if: ${{ inputs.fail == true }}
+        run: exit 1
+
+      - name: "Conditional Step - Success"
+        if: ${{ success() }}
+        run: echo "All previous steps succeeded."
+
+      - name: "Conditional Step - Failure"
+        if: ${{ failure() }}
+        run: echo "A previous step failed."
+
+      - name: "Print Always"
+        if: ${{ !cancelled() }}
+        run: echo "This step runs unless the workflow is cancelled."
+
+      - name: "On Cancel"
+        if: ${{ cancelled() }}
+        run: echo "Workflow cancelled."
+
